const lineupActionTypes={
    CHANGE_TEAM:'CHANGE_TEAM',
    CHANGE_POSITION:'CHANGE_POSITION',
    ADD_PLAYER:'ADD_PLAYER',
    DROP_PLAYER:'DROP_PLAYER',
    SET_TEAMS_FULL:'SET_TEAMS_FULL',
    SELECT_FORMAT:'SELECT_FORMAT'

}

export default lineupActionTypes